# ここでbaseのingress.yamlを上書きしている
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infra-workshop
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - oharu.she-dev.site
      secretName: infra-workshop-tls
  rules:
    - host: "oharu.she-dev.site"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: infra-workshop
                port:
                  number: 80
