apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-workshop

patchesStrategicMerge:
- ingress.yaml

resources:
- ../../base

replicas:
- count: 3
  name: infra-workshop-front
images:
- name: nextjs
  newName: aaaaaaa
  newTag: latest
