apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-workshop

# baseの内容にイングレスがけpathを当ててね？
patchesStrategicMerge:
- ingress.yaml

resources:
- ../../base

replicas:
- count: 3
  name: infra-workshop-front
# マニュフェストのimageタグを書き換えられる？今回はいらないかも
images:
- name: nextjs
  newName: 254476272534.dkr.ecr.ap-northeast-1.amazonaws.com/infra-workshop-front-oharu
  newTag: latest
