apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-workshop

patchesStrategicMerge:
  - ingress.yaml

resources:
  - ../../base

replicas:
  - name: infra-workshop-api
    count: 3
  - name: infra-workshop-front
    count: 3
