# httpsリクエストに対して証明書を返す必要がある
# それを簡単に返すためのしくみ
# issureにはネームスペースごとに作れるのと、クラスター全体のがある
# 今回はクラスターイシュアー
#
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt

# specがacmeだとこういう設定できる
# letsencrypt 無料の証明書発行
spec:
  acme:
    email: dev@she-inc.co.jp
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector:
          dnsZones:
            - "she-dev.site"
        dns01:
          route53:
            region: ap-northeast-1
