apiVersion: batch/v1
kind: Job
metadata:
  name: rails-migration
  labels:
    role: migration
spec:
  ttlSecondsAfterFinished: 43200
  template:
    metadata:
      labels:
        role: migration
    spec:
      containers:
        - name: rails-migration
          image: rails
          imagePullPolicy: IfNotPresent
          args:
            - bundle
            - exec
            - rails
            - db:migrate
          envFrom:
            - configMapRef:
                name: infra-workshop-configmap
            - secretRef:
                name: infra-workshop-secrets
      restartPolicy: OnFailure
