apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-workshop

resources:
- job.yaml
images:
- name: rails
  newName: 254476272534.dkr.ecr.ap-northeast-1.amazonaws.com/infra-workshop-api
  newTag: latest
