apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-workshop

configMapGenerator:
  - name: infra-workshop-configmap
    behavior: merge
    literals:
      - RAILS_ENV="production"
      - API_HOST="tajiri.she-dev.site"
      - DATABASE_HOST="terraform-20210907152434105500000001.clzertgkif0d.ap-northeast-1.rds.amazonaws.com"
      - DATABASE_USER="app_user"
      - DATABASE="infra_workshop"

resources:
  - ../../../configs

patchesStrategicMerge:
  - secrets.yaml
