apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: infra-workshop-secrets
spec:
  backendType: secretsManager
  region: ap-northeast-1
  data:
    - name: DATABASE_PASSWORD
      key: /infra-workshop-tajiri/databases
      property: password
    - name: RAILS_MASTER_KEY
      key: /infra-workshop-tajiri/rails
      property: master_key

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: infra-workshop-basic-auth
spec:
  backendType: secretsManager
  region: ap-northeash-1
  data:
    - name: auth
      key: /infra-workshop-tajiri/basic-auth
      property: auth
