apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: infra-workshop
  built-by: kustomize

resources:
  - serviceaccount.yaml
  - service.yaml
  - infra-workshop-api.yaml
  - infra-workshop-front.yaml
  - ingress.yaml
